/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;

/**
 *
 * @author Admin
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    
     
    public home() {
        initComponents();
         isinama.setText(register.name + " ♡⁠♡⁠♡⁠♡⁠");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selamatdatang = new javax.swing.JLabel();
        isinama = new javax.swing.JLabel();
        tasks = new javax.swing.JLabel();
        teksbuattask = new javax.swing.JLabel();
        aktivitas = new javax.swing.JLabel();
        keuangan = new javax.swing.JLabel();
        teksbuataktivitas = new javax.swing.JLabel();
        teksbuatkeuangan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        selamatdatang.setBackground(new java.awt.Color(255, 255, 255));
        selamatdatang.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        selamatdatang.setForeground(new java.awt.Color(255, 255, 255));
        selamatdatang.setText("Selamat Datang,");

        isinama.setBackground(new java.awt.Color(255, 255, 255));
        isinama.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        isinama.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isinama)
                    .addComponent(selamatdatang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(selamatdatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isinama)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formloginregister/gambar/goals.png"))); // NOI18N
        tasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasksMouseClicked(evt);
            }
        });

        teksbuattask.setBackground(new java.awt.Color(0, 153, 153));
        teksbuattask.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        teksbuattask.setForeground(new java.awt.Color(0, 153, 153));
        teksbuattask.setText("Task Manager");

        aktivitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formloginregister/gambar/calendar.png"))); // NOI18N
        aktivitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aktivitasMouseClicked(evt);
            }
        });

        keuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formloginregister/gambar/100-dollar-bill.png"))); // NOI18N
        keuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keuanganMouseClicked(evt);
            }
        });

        teksbuataktivitas.setBackground(new java.awt.Color(0, 153, 153));
        teksbuataktivitas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        teksbuataktivitas.setForeground(new java.awt.Color(0, 153, 153));
        teksbuataktivitas.setText("Activity Tracker");

        teksbuatkeuangan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        teksbuatkeuangan.setForeground(new java.awt.Color(0, 153, 153));
        teksbuatkeuangan.setText("Money Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teksbuataktivitas)
                .addGap(27, 27, 27)
                .addComponent(aktivitas)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tasks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teksbuattask))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keuangan)
                        .addGap(38, 38, 38)
                        .addComponent(teksbuatkeuangan)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tasks))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(teksbuattask)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(teksbuataktivitas)
                        .addGap(80, 80, 80)
                        .addComponent(keuangan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(aktivitas)
                        .addGap(81, 81, 81)
                        .addComponent(teksbuatkeuangan)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasksMouseClicked
          taskManager tm = new taskManager();
          tm.setVisible(true);
          tm.pack();
          tm.setLocationRelativeTo(null);
          tm.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
        // TODO add your handling code here:
    }//GEN-LAST:event_tasksMouseClicked

    private void aktivitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aktivitasMouseClicked
          activityTracker at = new activityTracker();
          at.setVisible(true);
          at.pack();
          at.setLocationRelativeTo(null);
          at.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
// TODO add your handling code here:
    }//GEN-LAST:event_aktivitasMouseClicked

    private void keuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keuanganMouseClicked
          moneyManager mm = new moneyManager();
          mm.setVisible(true);
          mm.pack();
          mm.setLocationRelativeTo(null);
          mm.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
// TODO add your handling code here:
    }//GEN-LAST:event_keuanganMouseClicked
    
   
    /**
     * @param args the command line arguments
     */
  
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aktivitas;
    private javax.swing.JLabel isinama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel keuangan;
    private javax.swing.JLabel selamatdatang;
    private javax.swing.JLabel tasks;
    private javax.swing.JLabel teksbuataktivitas;
    private javax.swing.JLabel teksbuatkeuangan;
    private javax.swing.JLabel teksbuattask;
    // End of variables declaration//GEN-END:variables
}
